CREATE VIEW [dbo].[V_SUB_SYSTEM_VIEW] AS
SELECT
	pl.PRODLINE,
	p.Product,
	i.PLIPMT,
	v.VERSION,
	r.release,
	s.*
FROM
	IBDS_SUB_SYSTEM s
	LEFT JOIN IBDS_Product p ON s.ProductNo= p.ProductNo
	LEFT JOIN IBDS_RELEASE r ON s.ProductNo = r.ProductNo
	LEFT JOIN IBDS_PRODLINE pl ON s.PRODLINENo= pl.PRODLINENo
	LEFT JOIN IBDS_PLIPMT i ON i.PLIPMTNo= s.PLIPMTNo
	LEFT JOIN IBDS_VERSION v ON s.VERSIONNo= v.VERSIONNo