	CREATE VIEW [dbo].[V_MODULE_VIEW] AS
	SELECT
	pl.PRODLINE,
	p.Product,
	i.PLIPMT,
	v.VERSION,
	r.release,
	s.SUBSYSTEM,
	m.*
FROM
	IBDS_MODULE m
	LEFT JOIN IBDS_Product p ON p.ProductNo = m.ProductNo
	LEFT JOIN IBDS_RELEASE r ON m.ProductNo = r.ProductNo
	LEFT JOIN IBDS_SUB_SYSTEM s ON s.SUBSYSTEMNo= m.SUBSYSTEMNo
	LEFT JOIN IBDS_VERSION v ON m.VERSIONNo= v.VERSIONNo
	LEFT JOIN IBDS_PRODLINE pl ON m.PRODLINENo= pl.PRODLINENo
	LEFT JOIN IBDS_PLIPMT i ON i.PLIPMTNo= m.PLIPMTNo