	CREATE VIEW [dbo].[V_MODULE_VERSION_VIEW] AS		
	SELECT
	pl.PRODLINE,
	p.Product,
	i.PLIPMT,
	v.VERSION,
	s.SUBSYSTEM,
	m.MODULE,
	r.release,
	mv.* 
FROM
	IBDS_MODULE_VERSION mv
	LEFT JOIN IBDS_Product p ON p.ProductNo = mv.ProductNo
	LEFT JOIN IBDS_RELEASE r ON mv.ProductNo = r.ProductNo
	LEFT JOIN IBDS_SUB_SYSTEM s ON s.SUBSYSTEMNo= mv.SUBSYSTEMNo
	LEFT JOIN IBDS_VERSION v ON mv.VERSIONNo= v.VERSIONNo
	LEFT JOIN IBDS_PRODLINE pl ON mv.PRODLINENo= pl.PRODLINENo
	LEFT JOIN IBDS_PLIPMT i ON i.PLIPMTNo= mv.PLIPMTNo
	LEFT JOIN IBDS_MODULE m ON mv.MODULENo = m.MODULENo